### ISSUE TITLE
Scrollbar is covered up by header element

### ISSUE THREAD

**Issue by Ajedi32** [Polymer/core-scroll-header-panel#44]
If you look at the [demo page](https://www.polymer-project.org/0.5/components/core-scroll-header-panel/demo.html) for this component (using Chrome 42, in my case), you'll see that the scroll bar is covered up by the toolbar when the toolbar is visible. Not only is this ugly, but it also makes it impossible to scroll up using the buttons on the scrollbar, since as as soon as you click the up arrow once, the toolbar appears and prevents you from clicking it again.

**Comment by Ajedi32** [comment]
Work around:

``` css
core-scroll-header-panel::shadow #headerContainer {
  margin-right: 17px;
}
```
